POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV1c2kgdXNlciIsImlkIjoiNjdiNGFjNTljNjk1ZWMyZjdmMGQ3ZjdhIiwiaWF0IjoxNzM5ODk1OTUzLCJleHAiOjE3Mzk4OTk1NTN9.ZQUC2qwIXtRUuJWnhl3kGWVcRx1TB-Sg-8LU9UmUVeY

{
  "title": "Toinen Blogilistan toiminta ohjeet ",
  "author": "Uusi User",
  "url": "https://toinenblogi.com",
  "likes": 5
}