DELETE http://localhost:3003/api/blogs/67ae2a39348553788ed5efe4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsImlkIjoiNjdhY2M3N2E5MDc2Nzc5YThlYzU5Mjg1IiwiaWF0IjoxNzM5NDY3NjA2LCJleHAiOjE3Mzk0NzEyMDZ9.joH15Jqep6mMVl5hlUiL4p2D2IPmIIcPpLxz1o2Z9YY