GET http://localhost:3003/api/blogs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV1c2kgdXNlciIsImlkIjoiNjdiNGFjNTljNjk1ZWMyZjdmMGQ3ZjdhIiwiaWF0IjoxNzM5ODk0Mjc4LCJleHAiOjE3Mzk4OTc4Nzh9.Hr-FBbqzy2IKsLZYiVgFsvcQQm0aDDmOvONLaWWkn2k