### 1. First login to get a fresh token
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "testuser1",
    "password": "password3331"
}

### 2. List all blogs to get the ID (use token from login)
GET http://localhost:3003/api/blogs
Authorization: Bearer {{login.response.body.token}}

### 3. Delete blog (use token from login)
DELETE http://localhost:3003/api/blogs/REPLACE_WITH_BLOG_ID
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}